// Shared navbar for study-note pages. Generated by tools/build_nav.py — edit tools/nav.template.js, not nav.js.
(function () {
  const DATA = {
 "sections": {
  "1": "AI Infrastructure Basics for Data Centers - 20%",
  "2": "Pre-Deployment Planning and Site Assessment for AI Data Centers - 11%",
  "3": "Rack Infrastructure Preparation for AI Platforms - 10%",
  "4": "High-Density Cabling Installation for AI Clusters - 30%",
  "5": "Cable Support Systems and Weight Management - 7%",
  "6": "Testing, Verification, and Documentation for AI Cabling - 12%",
  "7": "Safety, Standards, and Compliance for Data Centers - 10%"
 },
 "kinds": {
  "T": "Exam topics",
  "SR": "Suggested readings",
  "O": "Other"
 },
 "pages": [
  {
   "path": "1.T1/datacenter-cooling-no-raised-floor.html",
   "section": "1",
   "kind": "T",
   "code": "T1",
   "title": "No raised floor? Cooling a data center on a slab"
  },
  {
   "path": "1.T1/datacenter-direct-to-chip-cooling.html",
   "section": "1",
   "kind": "T",
   "code": "T1",
   "title": "Liquid to the chip: a beginner's guide to direct-to-chip cooling"
  },
  {
   "path": "1.T1/datacenter-formulas-guide.html",
   "section": "1",
   "kind": "T",
   "code": "T1",
   "title": "Data center formulas, from easy to deep"
  },
  {
   "path": "1.T1/datacenter-gb200-nvl72-guide.html",
   "section": "1",
   "kind": "T",
   "code": "T1",
   "title": "GB200 NVL72: one rack, 132 kW — power and cooling for beginners"
  },
  {
   "path": "1.T1/datacenter-power-cooling-guide.html",
   "section": "1",
   "kind": "T",
   "code": "T1",
   "title": "Power in, heat out: a beginner's guide to data center capacity"
  },
  {
   "path": "1.T2/ac-vs-dc-racks.html",
   "section": "1",
   "kind": "T",
   "code": "T2",
   "title": "AC vs DC powered racks"
  },
  {
   "path": "1.T3/balance-rpdus.html",
   "section": "1",
   "kind": "T",
   "code": "T3",
   "title": "Balancing rack PDUs"
  },
  {
   "path": "1.T4/rack-power-redundancy.html",
   "section": "1",
   "kind": "T",
   "code": "T4",
   "title": "Rack power redundancy"
  },
  {
   "path": "1.T5/pdu-power-capacity.html",
   "section": "1",
   "kind": "T",
   "code": "T5",
   "title": "PDU power capacity"
  },
  {
   "path": "1.T6/cdus-liquid-cooled-racks.html",
   "section": "1",
   "kind": "T",
   "code": "T6",
   "title": "CDUs for liquid-cooled racks"
  },
  {
   "path": "1.T7/verify-grounding.html",
   "section": "1",
   "kind": "T",
   "code": "T7",
   "title": "Verifying rack grounding"
  },
  {
   "path": "1.T8/hot-vs-cold-aisle.html",
   "section": "1",
   "kind": "T",
   "code": "T8",
   "title": "Hot vs. cold aisle"
  },
  {
   "path": "1.SR1/cold-aisle-containment-test.html",
   "section": "1",
   "kind": "SR",
   "code": "SR1",
   "title": "Test: Cold aisle containment"
  },
  {
   "path": "1.SR1/cold-aisle-containment.html",
   "section": "1",
   "kind": "SR",
   "code": "SR1",
   "title": "Cold aisle containment, explained in drawings"
  },
  {
   "path": "1.SR2/380Vdc_Architectures_Explained.html",
   "section": "1",
   "kind": "SR",
   "code": "SR2",
   "title": "380 Vdc Architectures for the Modern Data Center — Explained"
  },
  {
   "path": "1.SR3/intelligent-pdu-explained.html",
   "section": "1",
   "kind": "SR",
   "code": "SR3",
   "title": "Intelligent PDUs, explained with diagrams"
  },
  {
   "path": "1.SR4/3-phase-power-explained.html",
   "section": "1",
   "kind": "SR",
   "code": "SR4",
   "title": "3-Phase Power, Illustrated"
  },
  {
   "path": "1.SR5/alternating-phase-explained.html",
   "section": "1",
   "kind": "SR",
   "code": "SR5",
   "title": "Alternating phase PDUs, explained"
  },
  {
   "path": "1.SR6/nvent-cdu-explained.html",
   "section": "1",
   "kind": "SR",
   "code": "SR6",
   "title": "Coolant Distribution Units, explained — nVent CDU"
  },
  {
   "path": "1.SR7/server-rack-grounding.html",
   "section": "1",
   "kind": "SR",
   "code": "SR7",
   "title": "Grounding a Server Rack, Explained"
  },
  {
   "path": "1.SR8/nfpa-codes-explained.html",
   "section": "1",
   "kind": "SR",
   "code": "SR8",
   "title": "NFPA Codes & Standards List, Explained"
  },
  {
   "path": "1.SR9/sdf-explained.html",
   "section": "1",
   "kind": "SR",
   "code": "SR9",
   "title": "SDF explained: IEC 61523-3 / IEEE 1497"
  },
  {
   "path": "1.SR11/crac-aisle-containment-explained.html",
   "section": "1",
   "kind": "SR",
   "code": "SR11",
   "title": "CRAC with aisle containment, explained"
  },
  {
   "path": "1.O1/ai-datacenter-explainer.html",
   "section": "1",
   "kind": "O",
   "code": "O1",
   "title": "How AI changes data center design — an explainer of Schneider WP110"
  },
  {
   "path": "1.O1/eu-2019-424-servers-storage-explained.html",
   "section": "1",
   "kind": "O",
   "code": "O1",
   "title": "Regulation (EU) 2019/424 explained: ecodesign for servers and data storage"
  },
  {
   "path": "1.O1/liquid-cooling-explainer.html",
   "section": "1",
   "kind": "O",
   "code": "O1",
   "title": "Liquid cooling architectures for AI data centers, explained"
  },
  {
   "path": "2.T1/physical-network-design-docs.html",
   "section": "2",
   "kind": "T",
   "code": "T1",
   "title": "Physical network design docs"
  },
  {
   "path": "2.T2/cable-pathway-site-survey.html",
   "section": "2",
   "kind": "T",
   "code": "T2",
   "title": "Cable pathway site survey"
  },
  {
   "path": "2.T3/environmental-readiness.html",
   "section": "2",
   "kind": "T",
   "code": "T3",
   "title": "Environmental readiness"
  },
  {
   "path": "2.T4/inventory-check-procedures.html",
   "section": "2",
   "kind": "T",
   "code": "T4",
   "title": "Inventory check procedures"
  },
  {
   "path": "2.SR1/tia-606b-cable-labeling-explained.html",
   "section": "2",
   "kind": "SR",
   "code": "SR1",
   "title": "TIA-606-B cable labeling, explained visually"
  },
  {
   "path": "2.SR2/elevated_return_air_explainer.html",
   "section": "2",
   "kind": "SR",
   "code": "SR2",
   "title": "Elevated return air temperature, explained"
  },
  {
   "path": "2.SR3/nec-392-18F-cable-tray-access.html",
   "section": "2",
   "kind": "SR",
   "code": "SR3",
   "title": "NEC 392.18(F) Cable Tray Access, explained"
  },
  {
   "path": "2.SR4/breaker-80-vs-100-explained.html",
   "section": "2",
   "kind": "SR",
   "code": "SR4",
   "title": "80% vs 100% rated circuit breakers, explained"
  },
  {
   "path": "2.SR7/hot-aisle-cold-aisle-explained.html",
   "section": "2",
   "kind": "SR",
   "code": "SR7",
   "title": "Hot aisle / cold aisle layout, explained"
  },
  {
   "path": "2.SR8/nvidia-networking-explained.html",
   "section": "2",
   "kind": "SR",
   "code": "SR8",
   "title": "NVIDIA Networking, explained"
  },
  {
   "path": "3.SR1/data-center-design-explained.html",
   "section": "3",
   "kind": "SR",
   "code": "SR1",
   "title": "Energy-Efficient Data Center Design, Explained"
  },
  {
   "path": "3.SR2/dgx-h100-h200-guide-explained.html",
   "section": "3",
   "kind": "SR",
   "code": "SR2",
   "title": "DGX H100/H200 User Guide, explained"
  },
  {
   "path": "3.SR3/infiniband-cables-explained.html",
   "section": "3",
   "kind": "SR",
   "code": "SR3",
   "title": "InfiniBand cables, explained visually"
  },
  {
   "path": "3.SR4/wyr-grid-explained.html",
   "section": "3",
   "kind": "SR",
   "code": "SR4",
   "title": "Wyr-Grid Overhead Cable Tray — explained"
  },
  {
   "path": "3.SR5/nfpa70-explained.html",
   "section": "3",
   "kind": "SR",
   "code": "SR5",
   "title": "NFPA 70 (NEC) code development, explained"
  },
  {
   "path": "3.SR6/n93180ycfx-site-prep.html",
   "section": "3",
   "kind": "SR",
   "code": "SR6",
   "title": "Nexus 93180YC-FX: Preparing the Site, Explained"
  },
  {
   "path": "3.SR7/vertiv-rack-cooling-explained.html",
   "section": "3",
   "kind": "SR",
   "code": "SR7",
   "title": "Vertiv Rack Cooling, explained"
  },
  {
   "path": "3.SR7/vertiv-rack-cooling-explained2.html",
   "section": "3",
   "kind": "SR",
   "code": "SR7",
   "title": "Vertiv rack cooling, explained"
  },
  {
   "path": "3.SR8/intel-rack-compatibility-explained.html",
   "section": "3",
   "kind": "SR",
   "code": "SR8",
   "title": "Will this server fit this rack? Intel's rack compatibility guide, explained"
  },
  {
   "path": "3.SR8/intel_rack_compatibility_explained.html",
   "section": "3",
   "kind": "SR",
   "code": "SR8",
   "title": "Intel Server Rack Cabinet Compatibility Guide, explained"
  },
  {
   "path": "4.T1/nvidia-vs-other-cables.html",
   "section": "4",
   "kind": "T",
   "code": "T1",
   "title": "NVIDIA cables vs. others"
  },
  {
   "path": "4.T2/osfp-vs-qsfp-form-factors.html",
   "section": "4",
   "kind": "T",
   "code": "T2",
   "title": "OSFP vs. QSFP form factors"
  },
  {
   "path": "4.T3/mmf-vs-smf.html",
   "section": "4",
   "kind": "T",
   "code": "T3",
   "title": "MMF vs. SMF"
  },
  {
   "path": "4.T4/smf-transceiver-distances.html",
   "section": "4",
   "kind": "T",
   "code": "T4",
   "title": "SMF transceivers by distance"
  },
  {
   "path": "4.T5/infiniband-copper-cables.html",
   "section": "4",
   "kind": "T",
   "code": "T5",
   "title": "Deploying NDR/XDR copper"
  },
  {
   "path": "4.T6/mpo-apc-fiber-install.html",
   "section": "4",
   "kind": "T",
   "code": "T6",
   "title": "Installing MPO/APC fiber"
  },
  {
   "path": "4.T7/50-50-cable-routing.html",
   "section": "4",
   "kind": "T",
   "code": "T7",
   "title": "50/50 cable routing"
  },
  {
   "path": "4.T8/bundle-and-dress-cables.html",
   "section": "4",
   "kind": "T",
   "code": "T8",
   "title": "Bundling and dressing cables"
  },
  {
   "path": "4.T9/install-transceivers-clean-connectors.html",
   "section": "4",
   "kind": "T",
   "code": "T9",
   "title": "Transceivers and clean connectors"
  },
  {
   "path": "4.SR2/osfp-vs-qsfpdd-explained.html",
   "section": "4",
   "kind": "SR",
   "code": "SR2",
   "title": "OSFP vs QSFP-DD for 800G, explained"
  },
  {
   "path": "4.SR3/cable-management-best-practices.html",
   "section": "4",
   "kind": "SR",
   "code": "SR3",
   "title": "Cable Management Best Practices, explained"
  },
  {
   "path": "4.SR4/deploying-the-bundles-explained.html",
   "section": "4",
   "kind": "SR",
   "code": "SR4",
   "title": "Deploying the Bundles, explained — DGX SuperPOD cabling"
  },
  {
   "path": "4.SR5/ndr-connector-maintenance-explained.html",
   "section": "4",
   "kind": "SR",
   "code": "SR5",
   "title": "Keeping NDR optics clean — an explainer"
  },
  {
   "path": "4.SR6/nvidia-connectors-and-cages.html",
   "section": "4",
   "kind": "SR",
   "code": "SR6",
   "title": "Connectors and Cages, explained — NVIDIA LinkX"
  },
  {
   "path": "4.SR7/connectx7-cables-explained.html",
   "section": "4",
   "kind": "SR",
   "code": "SR7",
   "title": "ConnectX-7 validated cables & switches, explained"
  },
  {
   "path": "4.SR8/nvidia-xdr-switch-led-guide.html",
   "section": "4",
   "kind": "SR",
   "code": "SR8",
   "title": "Reading the LEDs on NVIDIA Q32xx / Q34xx XDR InfiniBand Switches"
  },
  {
   "path": "4.SR9/osfp-vs-qsfp-dd-explained.html",
   "section": "4",
   "kind": "SR",
   "code": "SR9",
   "title": "OSFP vs QSFP-DD, explained visually"
  },
  {
   "path": "4.SR10/200g-qsfp-dd-vs-osfp-explained.html",
   "section": "4",
   "kind": "SR",
   "code": "SR10",
   "title": "200G Transceivers: QSFP-DD vs OSFP, explained"
  },
  {
   "path": "4.SR11/single-mode-vs-multimode-fiber2.html",
   "section": "4",
   "kind": "SR",
   "code": "SR11",
   "title": "Single-mode vs multimode fiber, explained visually"
  },
  {
   "path": "4.SR12/single-mode-vs-multimode-fiber.html",
   "section": "4",
   "kind": "SR",
   "code": "SR12",
   "title": "Single-mode vs multimode fiber, explained"
  },
  {
   "path": "4.SR13/fiber-installation-mistakes.html",
   "section": "4",
   "kind": "SR",
   "code": "SR13",
   "title": "Two big mistakes in fiber cable installation — explained"
  },
  {
   "path": "4.SR14/single-mode-vs-multimode-fiber3.html",
   "section": "4",
   "kind": "SR",
   "code": "SR14",
   "title": "Single-mode vs multimode fiber, explained visually"
  },
  {
   "path": "4.SR15/mpo-mtp-cleaning-inspection.html",
   "section": "4",
   "kind": "SR",
   "code": "SR15",
   "title": "Cleaning and Inspecting MPO/MTP Connectors, Explained"
  },
  {
   "path": "4.SR16/foa-fiber-installation-explained.html",
   "section": "4",
   "kind": "SR",
   "code": "SR16",
   "title": "Fiber Optic Installation, Explained — FOA Guide"
  },
  {
   "path": "4.SR17/osfp-transceiver-install.html",
   "section": "4",
   "kind": "SR",
   "code": "SR17",
   "title": "Installing an OSFP transceiver — visual guide"
  },
  {
   "path": "4.SR18/iec-61300-3-35-explained.html",
   "section": "4",
   "kind": "SR",
   "code": "SR18",
   "title": "Clean & Inspect — IEC 61300-3-35 explained visually"
  },
  {
   "path": "5.SR1/dgx-superpod-h100-networking-explained.html",
   "section": "5",
   "kind": "SR",
   "code": "SR1",
   "title": "DGX SuperPOD H100 networking, explained: cables, trays and load"
  },
  {
   "path": "5.SR2/nvidia-cable-guidelines-explained.html",
   "section": "5",
   "kind": "SR",
   "code": "SR2",
   "title": "Cable Installation & Management, Explained"
  },
  {
   "path": "5.SR3/fiber-optic-installation-explained3.html",
   "section": "5",
   "kind": "SR",
   "code": "SR3",
   "title": "Fiber optic installation, explained — FOA Technical Bulletin"
  },
  {
   "path": "5.SR4/fiber-cable-installation-explained.html",
   "section": "5",
   "kind": "SR",
   "code": "SR4",
   "title": "Installing Fiber Optic Cable — Visual Explainer"
  },
  {
   "path": "5.SR4/fiber-cable-installation-explained2.html",
   "section": "5",
   "kind": "SR",
   "code": "SR4",
   "title": "Installing Fiber Optic Cable — Explained"
  },
  {
   "path": "6.T1/continuity-and-link-testing.html",
   "section": "6",
   "kind": "T",
   "code": "T1",
   "title": "Continuity and link testing"
  },
  {
   "path": "6.T2/final-quality-inspection.html",
   "section": "6",
   "kind": "T",
   "code": "T2",
   "title": "Final quality inspection"
  },
  {
   "path": "6.T3/document-as-built.html",
   "section": "6",
   "kind": "T",
   "code": "T3",
   "title": "Documenting the deployment"
  },
  {
   "path": "6.T4/signal-integrity-troubleshooting.html",
   "section": "6",
   "kind": "T",
   "code": "T4",
   "title": "Troubleshooting signal integrity"
  },
  {
   "path": "6.SR1/otdr-test-failures-explained.html",
   "section": "6",
   "kind": "SR",
   "code": "SR1",
   "title": "Diagnosing OTDR Test Failures — Explained"
  },
  {
   "path": "6.SR2/fiber-connector-contamination-explained.html",
   "section": "6",
   "kind": "SR",
   "code": "SR2",
   "title": "Dirty fiber connectors and poor I/O performance — explained"
  },
  {
   "path": "6.SR3/cumulus-layer1-troubleshooting-explained.html",
   "section": "6",
   "kind": "SR",
   "code": "SR3",
   "title": "Troubleshooting Layer 1 on Cumulus Linux — a visual guide"
  },
  {
   "path": "7.SR1/loto-8-steps-explained.html",
   "section": "7",
   "kind": "SR",
   "code": "SR1",
   "title": "Lockout–Tagout in 8 steps, explained"
  }
 ]
};
  if (!DATA || window.__studyNav) return;
  window.__studyNav = true;

  const script = document.currentScript;
  const base = new URL(".", script ? script.src : location.href);
  const here = decodeURIComponent(location.pathname);
  const idx = DATA.pages.findIndex((p) => here.endsWith("/" + p.path));
  const cur = DATA.pages[idx];
  const prev = idx > 0 ? DATA.pages[idx - 1] : null;
  const next = idx >= 0 && idx < DATA.pages.length - 1 ? DATA.pages[idx + 1] : null;
  const href = (p) => new URL(p.path, base).href;
  const esc = (s) => String(s).replace(/[&<>"]/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" }[c]));
  const secShort = (s) => (DATA.sections[s] || "Section " + s).replace(/\s*-?\s*\d+%\s*$/, "");

  const host = document.createElement("div");
  host.id = "study-nav";
  host.style.cssText = "all:initial;display:block;position:relative;z-index:2147483000";
  const root = host.attachShadow({ mode: "open" });

  // Group pages by section, then kind.
  let list = "";
  let lastSec = null, lastKind = null;
  for (const p of DATA.pages) {
    if (p.section !== lastSec) {
      if (lastSec !== null) list += "</ul></section>";
      list += `<section><h2>${esc(p.section)}. ${esc(secShort(p.section))}</h2><ul>`;
      lastSec = p.section; lastKind = null;
    }
    if (p.kind !== lastKind) {
      list += `<li class="kind">${esc(DATA.kinds[p.kind] || p.kind)}</li>`;
      lastKind = p.kind;
    }
    const on = p === cur ? ' aria-current="page"' : "";
    list += `<li><a href="${href(p)}"${on}><span class="code">${esc(p.code)}</span><span>${esc(p.title)}</span></a></li>`;
  }
  if (lastSec !== null) list += "</ul></section>";

  const arrow = (p, dir) => p
    ? `<a class="step" href="${href(p)}" title="${esc(p.section + "." + p.code + " — " + p.title)}">${dir < 0 ? "‹ Prev" : "Next ›"}</a>`
    : `<span class="step off">${dir < 0 ? "‹ Prev" : "Next ›"}</span>`;

  root.innerHTML = `
<style>
  :host { --bg:#ffffff; --fg:#1f2328; --muted:#656d76; --line:#d0d7de; --hover:#f3f4f6; --accent:#0969da; --accent-bg:#ddf4ff; }
  @media (prefers-color-scheme: dark) {
    :host { --bg:#161b22; --fg:#e6edf3; --muted:#8d96a0; --line:#30363d; --hover:#21262d; --accent:#4493f8; --accent-bg:#1f2d3d; }
  }
  * { box-sizing:border-box; }
  nav { font:14px/1.4 system-ui,-apple-system,"Segoe UI",Roboto,sans-serif; color:var(--fg); background:var(--bg);
        border-bottom:1px solid var(--line); padding:8px 16px; display:flex; flex-wrap:wrap; align-items:center; gap:8px 12px; }
  a { color:inherit; text-decoration:none; }
  .home { font-weight:600; padding:4px 8px; border-radius:6px; }
  .home:hover, .step:hover, button:hover { background:var(--hover); }
  .crumb { color:var(--muted); min-width:0; overflow:hidden; text-overflow:ellipsis; white-space:nowrap; flex:1 1 200px; }
  .crumb b { color:var(--fg); font-weight:600; }
  .actions { display:flex; gap:4px; margin-left:auto; }
  .step, button { font:inherit; color:inherit; background:none; border:1px solid var(--line); border-radius:6px; padding:4px 10px; cursor:pointer; white-space:nowrap; }
  .step.off { opacity:.4; cursor:default; }
  .panel { display:none; position:absolute; left:0; right:0; top:100%; max-height:min(70vh,640px); overflow:auto;
           background:var(--bg); border-bottom:1px solid var(--line); box-shadow:0 8px 24px rgba(0,0,0,.18); padding:8px 16px 16px;
           font:14px/1.4 system-ui,-apple-system,"Segoe UI",Roboto,sans-serif; color:var(--fg); }
  .panel.open { display:grid; grid-template-columns:repeat(auto-fit,minmax(min(100%,360px),1fr)); gap:0 32px; }
  h2 { font-size:13px; text-transform:uppercase; letter-spacing:.04em; color:var(--muted); margin:12px 0 4px; }
  ul { list-style:none; margin:0; padding:0; }
  li.kind { font-size:12px; color:var(--muted); margin:8px 0 2px; }
  li a { display:flex; gap:8px; padding:4px 6px; border-radius:6px; }
  li a:hover { background:var(--hover); }
  li a[aria-current] { background:var(--accent-bg); color:var(--accent); font-weight:600; }
  .code { flex:0 0 3.2em; color:var(--muted); font-variant-numeric:tabular-nums; }
  a:focus-visible, button:focus-visible { outline:2px solid var(--accent); outline-offset:1px; }
</style>
<nav aria-label="Study notes">
  <a class="home" href="${base.href}">⌂ NCP-ARI Notes</a>
  <span class="crumb">${cur ? `${esc(cur.section)}. ${esc(secShort(cur.section))} · <b>${esc(cur.code)}</b> · ${esc(cur.title)}` : ""}</span>
  <span class="actions">${arrow(prev, -1)}${arrow(next, 1)}<button type="button" aria-expanded="false" aria-controls="panel">All notes ▾</button></span>
</nav>
<div class="panel" id="panel">${list}</div>`;

  const btn = root.querySelector("button");
  const panel = root.getElementById("panel");
  const toggle = (open) => {
    panel.classList.toggle("open", open);
    btn.setAttribute("aria-expanded", String(open));
    const a = open && root.querySelector("[aria-current]");
    if (a) panel.scrollTop = a.offsetTop - panel.clientHeight / 2;
  };
  btn.addEventListener("click", (e) => { e.stopPropagation(); toggle(!panel.classList.contains("open")); });
  document.addEventListener("click", (e) => { if (!e.composedPath().includes(host)) toggle(false); });
  document.addEventListener("keydown", (e) => { if (e.key === "Escape") toggle(false); });

  document.body.prepend(host);
})();
